import React from 'react';
import {render,screen,fireEvent,waitFor,within} from '@testing-library/react';
import {createInstance} from 'i18next';
import {I18nextProvider,initReactI18next} from 'react-i18next';
import TemplateBuilder from './TemplateBuilder';
import CompletionMarkDialog from './CompletionMarkDialog';
import RecipientFields from './RecipientFields';
import api from '../../../api/signingTemplatesApi';
import {fromEditor,toEditor} from './nativeTemplateAdapter';
import he from '../../../i18n/locales/he.json';
import ar from '../../../i18n/locales/ar.json';
import en from '../../../i18n/locales/en.json';
jest.mock('./SigningSelect',()=>props=><select {...props}/>);
jest.mock('../../../api/signingTemplatesApi',()=>({__esModule:true,default:{contacts:jest.fn()}}));
jest.mock('../../../components/specializedComponents/signFiles/pdfViewer/PdfViewer',()=>()=> <div>Actual editor PDF surface</div>);
jest.mock('../../../components/specializedComponents/signFiles/LawyerStampPopup',()=>props=><button onClick={()=>props.onConfirm('combined-image')}>Capture combined image</button>);
async function language(lng){const i18n=createInstance();await i18n.use(initReactI18next).init({resources:{he:{translation:he},ar:{translation:ar},en:{translation:en}},lng,interpolation:{escapeValue:false}});return i18n;}
const types=['signature','email','phone','initials','text','date','checkbox','idnumber','lawyerStamp'];
if (!window.crypto) Object.defineProperty(window, 'crypto', { value: require('crypto').webcrypto });
test.each(['he','ar','en'])('template menu offers all incumbent fields and a separate automatic option in %s',async lng=>{
    const i18n=await language(lng);
    const definition={schemaVersion:2,name:'Three roles',locale:lng,roles:[{key:'renter',label:'Renter',stage:0,min:1,max:1,capacity:'personal'}],stages:[{key:'one',after:null}],documents:[{key:'agreement',name:'Agreement',sourceArtifactId:'source',sourceHash:'hash',fields:[{id:'sign1',type:'signature',roleKey:'renter',occurrence:0,pageNum:1,x:40,y:80,width:180,height:48,required:true}]}]};
    const adapter={pdf:jest.fn(async()=>new Blob(['pdf'])),save:jest.fn(async()=>({template:{id:'saved'}}))};
    render(<I18nextProvider i18n={i18n}><TemplateBuilder template={{definition:toEditor(definition)}} adapter={adapter} onBack={jest.fn()} onSaved={jest.fn()}/></I18nextProvider>);
    fireEvent.click(screen.getByRole('button',{name:i18n.t('signingV2.builder.next')}));await screen.findByText('Actual editor PDF surface');
    fireEvent.click(screen.getByTitle(i18n.t('signing.fieldSettings.addFieldForPage',{page:1})));
    for(const type of types)expect(screen.getByRole('button',{name:i18n.t(`signing.fields.${type==='idnumber'?'idNumber':type}`)})).toBeInTheDocument();
    expect(screen.getByRole('button',{name:i18n.t('signingV2.completionMark.title')})).toBeInTheDocument();
    fireEvent.click(screen.getByRole('button',{name:i18n.t('signing.fields.phone')}));
    fireEvent.click(screen.getByRole('button',{name:i18n.t('signingV2.builder.next')}));
    fireEvent.click(screen.getByRole('button',{name:i18n.t('signingV2.authoring.publish')}));
    await waitFor(()=>expect(adapter.save).toHaveBeenCalledTimes(1));
    const native=fromEditor(adapter.save.mock.calls[0][0],lng);
    expect(native.documents[0].fields[0]).toMatchObject(definition.documents[0].fields[0]);
    expect(native.documents[0].fields[1]).toMatchObject({type:'phone',roleKey:'renter',required:true});
});
test('completion image authorization is explicit and is reset when the image changes',async()=>{
    const i18n=await language('en'),confirm=jest.fn(async()=>{});
    render(<I18nextProvider i18n={i18n}><CompletionMarkDialog onClose={jest.fn()} onConfirm={confirm}/></I18nextProvider>);
    expect(screen.getByRole('heading',{name:i18n.t('signingV2.completionMark.title')}).closest('.lw-templates')).toHaveAttribute('dir','ltr');
    const select=await screen.findByLabelText(i18n.t('signingV2.completionMark.kind'));
    fireEvent.change(select,{target:{value:'combined'}});fireEvent.click(screen.getByRole('button',{name:'Capture combined image'}));
    const add=screen.getByRole('button',{name:i18n.t('signingV2.completionMark.add')});expect(add).toBeDisabled();
    fireEvent.click(screen.getByLabelText(i18n.t('signingV2.completionMark.authorize')));expect(add).toBeEnabled();
    fireEvent.click(screen.getByRole('button',{name:'Capture combined image'}));expect(add).toBeDisabled();
    fireEvent.click(screen.getByLabelText(i18n.t('signingV2.completionMark.authorize')));fireEvent.click(add);
    await waitFor(()=>expect(confirm).toHaveBeenCalledWith({kind:'combined',image:'combined-image',authorized:true}));
});
test.each(['he','ar','en'])('every legacy recipient role can search managers/lawyers/clients and enter an external person in %s',async lng=>{
    const i18n=await language(lng),change=jest.fn();
    api.contacts.mockResolvedValue({contacts:[{userId:1,name:'Office manager',email:'manager@example.invalid'},{userId:2,name:'Existing client',email:'client@example.invalid'}]});
    render(<I18nextProvider i18n={i18n}><RecipientFields role={{name:'Lawyer',kind:'lawyer'}} onChange={change}/></I18nextProvider>);
    fireEvent.change(screen.getByPlaceholderText(i18n.t('signingV2.compose.searchRecipients')),{target:{value:'Existing'}});
    await screen.findByRole('button',{name:/Office manager/});
    expect(api.contacts).toHaveBeenCalledWith('Existing');expect(api.contacts.mock.calls[0]).toHaveLength(1);
    fireEvent.click(screen.getByRole('button',{name:/Existing client/}));expect(change).toHaveBeenLastCalledWith(expect.objectContaining({userId:2}));
    const form=screen.getByRole('group',{name:'Lawyer'});
    fireEvent.change(within(form).getByLabelText(i18n.t('signingV2.compose.fields.name')),{target:{value:'External signer'}});
    expect(change).toHaveBeenLastCalledWith({name:'External signer'});
});
