const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');const {normalizeRolePermissions}=require('../lib/firmRolePermissions');
function scope(shared=false){const filename=path.resolve(__dirname,'../lib/firmPermissions/caseScope.js'),m={exports:{}};const calls=[];vm.runInNewContext(fs.readFileSync(filename,'utf8'),{module:m,require(id){if(id==='../../config/db')return {query:async(sql,params)=>{calls.push({sql,params});return {rows:[]}}};if(id==='../tenant/tenantContext')return {isMultiTenantMode:()=>shared};return require(path.resolve(path.dirname(filename),id))}});return {...m.exports,calls}}
const request=(role,ds)=>({firmPermissionMode:'role',firmPermissionContextValidated:true,firmTenantId:'A',user:{UserId:1,Role:role},firmPermissions:normalizeRolePermissions({areas:{cases:{visible:true,actions:['view','edit'],dataScope:ds}}})});
for(const role of ['Admin','Lawyer'])for(const ds of ['assigned_only','all_firm'])test(`case ${role}/${ds} parameterized tenant scope and pagination`,async()=>{const s=scope(true),r=request(role,ds);await s.queryScopedCases(r,'SELECT C.caseid FROM cases C ORDER BY C.caseid LIMIT $1 OFFSET $2',[20,0]);const q=s.calls[0];assert.match(q.sql,/law_firm_tenant_id.*IS NOT DISTINCT FROM \$3::text/);assert.equal(q.params[2],'A');assert.equal(q.sql.includes('scope_membership'),ds==='assigned_only');if(ds==='assigned_only')assert.equal(q.params[3],1)});
test('shared missing tenant stops before query; legacy query unchanged',async()=>{const s=scope(true),r=request('Admin','all_firm');r.firmTenantId=null;await assert.rejects(s.queryScopedCases(r,'SELECT C.caseid FROM cases C'),e=>e.httpStatus===403);assert.equal(s.calls.length,0);await s.queryScopedCases({firmPermissionMode:'legacy'},'SELECT C.caseid FROM cases C',[1]);assert.equal(s.calls[0].sql,'SELECT C.caseid FROM cases C')});
test('case controller list functions use scoped query, including name and tagged lookups',()=>{const src=fs.readFileSync(path.resolve(__dirname,'../controllers/caseController.js'),'utf8');for(const name of ['getCases','getCaseByName','getTaggedCases','getTaggedCasesByName','getMyCases']){const start=src.indexOf('const '+name+' ='),end=src.indexOf('\n};',start),part=src.slice(start,end);assert.match(part,/queryScopedCases\(req,/);assert.equal(part.includes('await pool.query('),false,name)}});
test('case tenancy is canonical record field, not manager or stale membership',()=>{for(const ds of ['assigned_only','all_firm']){const s=scope(true),f=s.caseScopeFilter(request('Admin',ds));assert.match(f.sql,/to_jsonb\(scope_case\).*law_firm_tenant_id/);assert.equal(f.sql.includes('scope_manager'),false);const rowAllows=(row,user=1,tenant='A')=>(row.law_firm_tenant_id??null)===tenant&&(ds==='all_firm'||row.casemanagerid===user||row.members?.includes(user));assert.equal(rowAllows({law_firm_tenant_id:'B',casemanagerid:1,members:[1]}),false);assert.equal(rowAllows({law_firm_tenant_id:null,casemanagerid:1,members:[1]}),false);if(ds==='all_firm'){assert.equal(rowAllows({law_firm_tenant_id:'A',casemanagerid:null}),true);assert.equal(rowAllows({law_firm_tenant_id:'A',casemanagerid:999999}),true)}}});
test('dedicated null tenant preserves existing all scope with absent/deleted manager',()=>{const s=scope(false),r=request('Admin','all_firm');r.firmTenantId=null;const f=s.caseScopeFilter(r);assert.deepEqual(Array.from(f.params),[null]);assert.equal(f.sql.includes('casemanagerid'),false);assert.equal(f.sql.includes('case_users'),false)});
test('unpaginated SQL retains dollar binds rather than replacement captures',async()=>{const s=scope(),r=request('Admin','assigned_only');await s.queryScopedCases(r,'SELECT C.caseid FROM cases C ORDER BY C.caseid',[]);const q=s.calls[0];assert.match(q.sql,/IS NOT DISTINCT FROM \$1::text/);assert.match(q.sql,/casemanagerid = \$2/);assert.equal(q.sql.includes('IS NOT DISTINCT FROM C::text'),false)});
