const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const jwt=require('jsonwebtoken');const root=path.resolve(__dirname,'..');const secret='local-recovery-test-not-a-credential';
function loadMiddleware(currentRole,tenant='A',missing=false){const filename=path.join(root,'middlewares/attachFirmPermissions.js'),m={exports:{}};const calls=[];vm.runInNewContext(fs.readFileSync(filename,'utf8'),{module:m,require(id){if(id==='../config/db')return {query:async(sql,params)=>{calls.push(sql);if(sql.includes('firm_staff_roles'))throw Object.assign(new Error('missing staff schema'),{code:'42P01'});return {rows:missing?[]:[{userid:1,role:currentRole,law_firm_tenant_id:tenant}]}}};return require(path.resolve(path.dirname(filename),id))}});return {fn:m.exports,calls}}
async function run(role,current=role,tenant='A',requestedTenant=undefined,missing=false){const m=loadMiddleware(current,tenant,missing),req={user:{UserId:1,Role:role},tenant:requestedTenant?{id:requestedTenant}:undefined};let error;await m.fn(req,{},e=>error=e);return {req,error,...m}}
for(const role of ['User','Client','ExternalSigner'])test(`customer ${role} stays customer and does not load staff schema`,async()=>{const x=await run(role);assert.equal(x.error,undefined);assert.equal(x.req.user.Role,role);assert.equal(x.req.firmPermissionMode,'legacy');assert.equal(x.req.firmTenantId,'A');assert.equal(x.req.isPlatformAdminUser,false);assert.equal(x.calls.length,1);assert.equal(x.calls.some(sql=>sql.includes('firm_staff_roles')),false)});
for(const role of ['Admin','Lawyer','Staff','Deleted'])test(`stale customer JWT after DB role ${role} cannot bypass loader`,async()=>assert.equal((await run('User',role)).error.httpStatus,401));
test('cross requested tenant customer denied; correct tenant allowed',async()=>{assert.equal((await run('User','User','A','B')).error.httpStatus,403);assert.equal((await run('User','User','A','A')).error,undefined)});
test('removed customer is unauthorized',async()=>assert.equal((await run('User','User','A',undefined,true)).error.httpStatus,401));
for(const role of ['Admin','Lawyer','Staff'])test(`staff ${role} retains schema fail closed`,async()=>assert.equal((await run(role)).error.code,'42P01'));
function optional(currentRole){const gate=loadMiddleware(currentRole),filename=path.join(root,'middlewares/optionalAuthMiddleware.js'),m={exports:{}};vm.runInNewContext(fs.readFileSync(filename,'utf8'),{module:m,process:{env:{JWT_SECRET:secret}},require(id){if(id==='jsonwebtoken')return jwt;if(id==='./attachFirmPermissions')return gate.fn;return require(path.resolve(path.dirname(filename),id))}});return {...gate,fn:m.exports}}
for(const role of ['User','Client','ExternalSigner'])test(`actual HS256 signed public optional ${role} remains usable`,async()=>{const m=optional(role),req={headers:{authorization:'Bearer '+jwt.sign({userid:1,role},secret,{algorithm:'HS256',expiresIn:60})}};let error;await m.fn(req,{},e=>error=e);assert.equal(error,undefined);assert.equal(req.user.Role,role);assert.equal(m.calls.length,1)});
for(const token of [jwt.sign({userid:1,role:'User'},secret,{algorithm:'HS256',expiresIn:-1}),jwt.sign({userid:1,role:'User'},'wrong-secret'),jwt.sign({userid:1,role:'Admin'},secret,{algorithm:'HS384'}),'malformed'])test(`invalid optional token never supplies identity ${token.slice(0,12)}`,async()=>{const m=optional('User'),req={headers:{authorization:'Bearer '+token}};let error;await m.fn(req,{},e=>error=e);assert.equal(error,undefined);assert.equal(req.user,undefined);assert.equal(m.calls.length,0)});
test('optional valid staff JWT missing schema denies before handler',async()=>{const m=optional('Admin'),req={headers:{authorization:'Bearer '+jwt.sign({userid:1,role:'Admin'},secret)}};let error;await m.fn(req,{},e=>error=e);assert.equal(error.code,'42P01')});

for(const role of ['User','Client','ExternalSigner'])test(`customer enum change uses current DB role ${role} without staff promotion`,async()=>{const x=await run('User',role);assert.equal(x.error,undefined);assert.equal(x.req.user.Role,role);assert.equal(x.req.firmPermissionMode,'legacy');assert.equal(x.req.isPlatformAdminUser,false);assert.equal(x.calls.some(sql=>sql.includes('firm_staff_roles')),false)});
