const test=require('node:test'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');
const{deliveryHarness}=require('./helpers/signingV2Delivery');const replacement=require('../services/signingV2/replacement'),contacts=require('../services/signingV2/contactChanges');
test('new source profile correction invalidates open replacement review and publish',{skip:process.env.LEGAL_DB_QA!=='true',timeout:20000},async t=>{
 const pool=require('../config/db');t.after(()=>pool.end());const h=await deliveryHarness(pool,{endpoints:['profile-review@example.invalid'],documentCount:1});t.after(h.close);
 await h.submit();await h.activate();const pkg=(await pool.query('SELECT id FROM signing_packages WHERE owner_context_id=$1',[h.f.contextId])).rows[0].id,scope={...h.f.scope,packageRevise:true,contactCorrect:true};
 const read=await replacement.readReplacement(pool,scope,pkg),profile=(await pool.query('SELECT person_id FROM signing_delivery_profiles WHERE owner_context_id=$1',[scope.contextId])).rows[0];
 const change=async endpoint=>{const c=await contacts.readContact(pool,scope,pkg,profile.person_id);return contacts.correctContact(pool,scope,pkg,profile.person_id,{revisionId:c.revisionId,expectedVersion:c.version,endpoints:{email:endpoint},reason:'Synthetic correction during review',idempotencyKey:randomUUID()});};
 await change('new-source@example.invalid');await assert.rejects(replacement.startReplacement(pool,scope,pkg,{expectedRevisionId:read.revisionId,expectedPackageVersion:read.packageVersion,sourceReviewHash:read.sourceReviewHash,reason:'review source',stopCurrent:false,idempotencyKey:randomUUID()}),{errorCode:'VERSION_CHANGED'});
 const fresh=await replacement.readReplacement(pool,scope,pkg);await replacement.startReplacement(pool,scope,pkg,{expectedRevisionId:fresh.revisionId,expectedPackageVersion:fresh.packageVersion,sourceReviewHash:fresh.sourceReviewHash,reason:'review source',stopCurrent:false,idempotencyKey:randomUUID()});
 const editing=await replacement.readReplacement(pool,scope,pkg),input={content:editing.content,reason:'review source',expectedRevisionId:editing.revisionId,expectedPackageVersion:editing.packageVersion},preview=await replacement.previewReplacement(pool,scope,pkg,input);assert.equal(preview.valid,true,JSON.stringify(preview.errors));await change('final-source@example.invalid');
 await assert.rejects(replacement.executeReplacement(pool,scope,pkg,{...input,previewHash:preview.previewHash,idempotencyKey:randomUUID()},{reserveCapacity:async()=>{}}),{errorCode:'PREVIEW_CHANGED'});assert.equal((await pool.query('SELECT count(*)::int n FROM signing_package_revisions WHERE package_id=$1',[pkg])).rows[0].n,1);
});
