const test = require('node:test');const assert = require('node:assert/strict');const crypto = require('node:crypto');const request = require('supertest');
test('batch reminders group documents, respect existing toggle and offset, claim once and preserve uncertain outcomes', { skip: process.env.LEGAL_DB_QA !== 'true', timeout: 60000 }, async t => {
    const f = await require('./helpers/signingTemplateFixture').signingTemplateFixture();
    const settings = require('../services/settingsService');
    const reminders = require('../lib/signingFileReminders');
    const service = require('../services/signingBatchReminders');
    const original = await f.pool.query("SELECT * FROM platform_settings WHERE category='signing' AND setting_key IN ('SIGN_REMINDER_AUTO_ENABLED','SIGN_REMINDER_OFFSET_HOURS')");
    t.after(async () => { for (const row of original.rows) await settings.upsertSetting(row.category, row.setting_key, row.setting_value, { valueType: row.value_type });await f.pool.end(); });
    await settings.upsertSetting('signing', 'SIGN_REMINDER_AUTO_ENABLED', 'true', { valueType: 'boolean' });
    await settings.upsertSetting('signing', 'SIGN_REMINDER_OFFSET_HOURS', '2', { valueType: 'number' });
    const auth = req => req.set('Authorization', `Bearer ${f.token}`);
    const ok = response => { assert.ok(response.status < 300, JSON.stringify({ status: response.status, body: response.body }));return response.body; };
    const definition = { ...f.definition, roles: [f.definition.roles[0]], documents: [0, 1].map(index => ({ ...f.definition.documents[0], id: crypto.randomUUID(), name: `Synthetic ${index}`, fields: [f.definition.documents[0].fields[0]] })) };
    const template = ok(await auth(request(f.app).post('/api/signing-templates')).send(definition)).template;
    const batch = ok(await auth(request(f.app).post('/api/signing-batches')).send({ templateId: template.id, templateVersion: 1, idempotencyKey: crypto.randomUUID(), packages: [{ signers: { first: { userId: f.users[1].userid, deliveryMethod: 'email' } } }] })).batch;
    const data = ok(await auth(request(f.app).post(`/api/signing-batches/${batch.id}/send`)).send({}));
    const recipient = data.recipients[0];
    let rows = (await f.pool.query('SELECT * FROM signing_batch_reminders WHERE recipient_id=$1', [recipient.id])).rows;
    assert.equal(rows.length, 1, 'two documents schedule one reminder for this signer');
    assert.equal(rows[0].scheduled_for - rows[0].invited_at, 2 * 3600000);
    ok(await auth(request(f.app).post(`/api/signing-batches/${batch.id}/send`)).send({}));
    assert.equal((await f.pool.query('SELECT * FROM signing_batch_reminders WHERE recipient_id=$1', [recipient.id])).rowCount, 1, 'dispatch retry does not reschedule or duplicate reminder');
    await reminders.rescheduleUnmodifiedReminders(6);
    rows = (await f.pool.query('SELECT * FROM signing_batch_reminders WHERE recipient_id=$1', [recipient.id])).rows;
    assert.equal(rows[0].scheduled_for - rows[0].invited_at, 6 * 3600000);
    await f.pool.query("UPDATE signing_batch_reminders SET scheduled_for=now()-interval '1 second' WHERE recipient_id=$1", [recipient.id]);
    const before = f.deliveries.length;
    await Promise.all([service.processDueBatchReminders(), service.processDueBatchReminders()]);
    assert.equal(f.deliveries.length - before, 1, 'concurrent workers send exactly one grouped reminder');
    const message = f.deliveries.at(-1);assert.equal(message.notificationType, 'SIGN_REMINDER');assert.equal(message.sms, null);
    assert.equal(new URL(message.email.contactFields.action_url).pathname, '/ViewSignedDocument/Package');
    await service.scheduleBatchReminder(recipient.id, new Date(Date.now() - 10000000));
    await reminders.cancelAllAutoManagedPending();
    assert.equal((await f.pool.query("SELECT * FROM signing_batch_reminders WHERE recipient_id=$1 AND status='pending'", [recipient.id])).rowCount, 0);
    await settings.upsertSetting('signing', 'SIGN_REMINDER_AUTO_ENABLED', 'false', { valueType: 'boolean' });
    assert.equal(await service.scheduleBatchReminder(recipient.id), 0);
    await settings.upsertSetting('signing', 'SIGN_REMINDER_AUTO_ENABLED', 'true', { valueType: 'boolean' });
    await service.scheduleBatchReminder(recipient.id, new Date(Date.now() - 20000000));
    await f.pool.query("UPDATE signing_batch_reminders SET scheduled_for=now()-interval '1 second' WHERE recipient_id=$1 AND status='pending'", [recipient.id]);
    f.outbound.mode = 'throw';await service.processDueBatchReminders();const count = f.deliveries.length;
    f.outbound.mode = 'success';await service.processDueBatchReminders();assert.equal(f.deliveries.length, count, 'uncertain reminder is not resent');
    assert.equal((await f.pool.query("SELECT * FROM signing_batch_reminders WHERE recipient_id=$1 AND status='uncertain'", [recipient.id])).rowCount, 1);
});
