const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const {normalizeRolePermissions,getCatalogForApi,getSigningDataScope,buildSessionScopeFromPermissions}=require('../lib/firmRolePermissions');
const filename=path.resolve(__dirname,'../lib/firmPermissions/signingAccess.js');
function access(rows,shared=false){const mod={exports:{}};let calls=[];vm.runInNewContext(fs.readFileSync(filename,'utf8'),{module:mod,Map,Set,require(id){if(id==='../../config/db')return {query:async(sql,params)=>{calls.push({sql,params});const id=params.at(-1),tenant=params[0],owner=params.length===3?params[1]:null;return {rows:rows.filter(f=>f.signingfileid===id&&f.tenant===tenant&&(owner===null||f.lawyerid===owner))}}};if(id==='../tenant/tenantContext')return {isMultiTenantMode:()=>shared};return require(path.resolve(path.dirname(filename),id))}});return {...mod.exports,calls}}
function req(role,scope,actions=['view','manage']){return {user:{UserId:1,Role:role},firmPermissionMode:'role',firmPermissionContextValidated:true,firmTenantId:'A',firmPermissions:normalizeRolePermissions({areas:{signing:{visible:true,actions,dataScope:scope}}}),params:{signingFileId:10}}}
const files=[{signingfileid:10,lawyerid:1,tenant:'A'},{signingfileid:11,lawyerid:2,tenant:'A'},{signingfileid:12,lawyerid:3,tenant:'B'}];
test('catalog and session expose independent signing scope',()=>{assert.equal(getCatalogForApi().areas.find(a=>a.id==='signing').supportsDataScope,true);const perms=normalizeRolePermissions({areas:{signing:{visible:true,actions:['view'],dataScope:'all_firm'},cases:{visible:false}}});assert.equal(getSigningDataScope(perms),'all_firm');assert.equal(buildSessionScopeFromPermissions(perms).signingDataScope,'all_firm')});
test('old or invalid signing scope defaults to own; never widens',()=>{for(const ds of [undefined,'global','all'])assert.equal(getSigningDataScope(normalizeRolePermissions({areas:{signing:{visible:true,actions:['view'],dataScope:ds}}})),'assigned_only')});
for(const role of ['Admin','Lawyer','Staff'])for(const scope of ['assigned_only','all_firm'])test(`${role}/${scope} direct record allow deny and tenant bound`,async()=>{const a=access(files,true),r=req(role,scope);assert.equal(await a.assertSigningFileOfficeAccess(r,10,'manage'),null);assert.equal(a.hasVerifiedSigningAction(r,{SigningFileId:10},'manage'),true);assert.equal(a.hasVerifiedSigningAction(r,{SigningFileId:11},'manage'),false);const other=await a.assertSigningFileOfficeAccess(r,11,'manage');assert.equal(other===null,scope==='all_firm');assert.equal((await a.assertSigningFileOfficeAccess(r,12,'manage')).httpStatus,403);for(const q of a.calls){assert.match(q.sql,/law_firm_tenant_id IS NOT DISTINCT FROM \$1::uuid/);assert.equal(q.params[0],'A')}});
test('missing tenant in shared deployment denies before database',async()=>{const a=access(files,true),r=req('Admin','all_firm');r.firmTenantId=null;assert.equal((await a.assertSigningFileOfficeAccess(r,10)).httpStatus,403);assert.equal(a.calls.length,0)});
test('denied page/action overrides owner and Admin title',async()=>{for(const role of ['Admin','Lawyer']){const a=access(files),r=req(role,'all_firm',['view']);assert.equal((await a.assertSigningFileOfficeAccess(r,10,'manage')).httpStatus,403);assert.equal(a.calls.length,0);r.firmPermissions.areas.signing.visible=false;assert.equal((await a.assertSigningFileOfficeAccess(r,10,'view')).httpStatus,403)}});
test('office query request cannot widen own scope; mine narrows all scope',()=>{const a=access([]);for(const role of ['Admin','Lawyer']){const own=a.signingScopeFilter(req(role,'assigned_only'));assert.equal(own.own,true);assert.deepEqual(Array.from(own.params),['A',1]);const all=a.signingScopeFilter(req(role,'all_firm'));assert.equal(all.own,false);assert.deepEqual(Array.from(all.params),['A']);const mine=a.signingScopeFilter(req(role,'all_firm'),{forceMine:true});assert.equal(mine.own,true)}});
test('controller helpers require current record-scoped grant before owner/Admin bypass',()=>{const a=access([]);const source=fs.readFileSync(path.resolve(__dirname,'../controllers/signingFileController.js'),'utf8');const start=source.indexOf('function isSigningOfficeStaffRole('),end=source.indexOf('function normalizeSignerDeliveryMethod(',start);const c={require:()=>a};vm.runInNewContext(source.slice(start,end),c);for(const role of ['Admin','Lawyer']){const r=req(role,'all_firm'),file={SigningFileId:10,LawyerId:1};assert.equal(c.canManageSigningFile({file,requesterId:1,role,req:r}),false);assert.equal(c.canViewSigningFileAsOfficeStaff({file,requesterId:1,role,req:r}),false);r.firmSigningAccess=new Map([[10,new Set(['manage','view'])]]);assert.equal(c.canManageSigningFile({file,requesterId:1,role,req:r}),true);assert.equal(c.canViewAllSigningSpots({file,requesterId:1,role,req:r}),true);assert.equal(c.canManageSigningFile({file:{SigningFileId:11,LawyerId:1},requesterId:1,role,req:r}),false)}});
test('list builder uses scope filter and correct paginated bind positions',()=>{const source=fs.readFileSync(path.resolve(__dirname,'../controllers/signingFileController.js'),'utf8');const start=source.indexOf('function buildLawyerSigningFilesListQuery('),end=source.indexOf('function isSigningDebugEnabled(',start);const c={};vm.runInNewContext(source.slice(start,end),c);for(const scope of ['assigned_only','all_firm']){const filter=access([]).signingScopeFilter(req('Admin',scope));const sql=c.buildLawyerSigningFilesListQuery({scope:'office',pagination:{enabled:true},customFilter:filter});assert.ok(sql.includes(filter.sql));assert.ok(sql.includes(`limit $${filter.params.length+1} offset $${filter.params.length+2}`));assert.equal(sql.includes("owner_u2.role in ('Admin', 'Lawyer')"),false)}});
test('associated case must match canonical tenant; null association is supported',()=>{const a=access([]),f=a.signingScopeFilter(req('Admin','all_firm'));assert.match(f.sql,/sf.caseid IS NULL OR EXISTS/);assert.match(f.sql,/to_jsonb\(scope_file_case\).*law_firm_tenant_id/)});
test('verified grant cannot authorize body/query record mismatch or wrong action',async()=>{const a=access(files),r=req('Admin','all_firm');assert.equal(await a.assertSigningFileOfficeAccess(r,10,'view'),null);r.body={signingFileId:11};r.query={signingFileId:12};assert.equal(a.hasVerifiedSigningAction(r,{SigningFileId:11},'view'),false);assert.equal(a.hasVerifiedSigningAction(r,{SigningFileId:10},'manage'),false);r.params.signingFileId=11;assert.equal(a.hasVerifiedSigningAction(r,{},'view'),false)});
test('persisted v1 case-wide signing roles keep explicit scope until edited',()=>{const old=normalizeRolePermissions({version:1,areas:{signing:{visible:true,actions:['view']},cases:{visible:true,actions:['view'],dataScope:'all_firm'}}});assert.equal(getSigningDataScope(old),'all_firm');const assigned=normalizeRolePermissions({version:1,areas:{signing:{visible:true,actions:['view']},cases:{visible:true,actions:['view'],dataScope:'assigned_only'}}});assert.equal(assigned.areas.signing.legacyCaseAssignment,true);const r=req('Lawyer','assigned_only');r.firmPermissions=assigned;assert.match(access([]).signingScopeFilter(r).sql,/signing_assignment.caseid = sf.caseid/);const edited=normalizeRolePermissions({version:2,areas:assigned.areas});assert.equal(edited.areas.signing.legacyCaseAssignment,undefined)});
test('scope requires authenticated office context, not only a null tenant',()=>{const a=access([]),r=req('Admin','all_firm');r.firmTenantId=null;r.firmPermissionContextValidated=false;assert.equal(a.signingScopeFilter(r).error.httpStatus,403)});
