-- Creates the base Signing schema (tables + core constraints/indexes) for production.
-- Production-safe and idempotent:
-- - Creates tables only if missing
-- - Adds required columns only if missing
-- - Adds constraints/indexes only if missing
--
-- This migration is intentionally additive (no drops).

-- 1) signingfiles
CREATE TABLE IF NOT EXISTS public.signingfiles (
    signingfileid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caseid INTEGER,
    lawyerid INTEGER NOT NULL,
    clientid INTEGER NOT NULL,
    filename TEXT NOT NULL,
    filekey TEXT,
    originalfilekey TEXT,
    status TEXT,
    notes TEXT,
    createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expiresat TIMESTAMPTZ,
    signedfilekey TEXT,
    signedat TIMESTAMPTZ,
    rejectionreason TEXT
);

-- Ensure required columns exist even if the table pre-existed.
ALTER TABLE IF EXISTS public.signingfiles
    ADD COLUMN IF NOT EXISTS caseid INTEGER,
    ADD COLUMN IF NOT EXISTS lawyerid INTEGER,
    ADD COLUMN IF NOT EXISTS clientid INTEGER,
    ADD COLUMN IF NOT EXISTS filename TEXT,
    ADD COLUMN IF NOT EXISTS filekey TEXT,
    ADD COLUMN IF NOT EXISTS originalfilekey TEXT,
    ADD COLUMN IF NOT EXISTS status TEXT,
    ADD COLUMN IF NOT EXISTS notes TEXT,
    ADD COLUMN IF NOT EXISTS createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS expiresat TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS signedfilekey TEXT,
    ADD COLUMN IF NOT EXISTS signedat TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS rejectionreason TEXT;

-- Ensure the canonical FK names exist (so later migrations that DROP/ADD by name are safe).
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'signingfiles_caseid_fkey'
    ) THEN
        ALTER TABLE public.signingfiles
            ADD CONSTRAINT signingfiles_caseid_fkey
            FOREIGN KEY (caseid) REFERENCES public.cases(caseid)
            ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'signingfiles_lawyerid_fkey'
    ) THEN
        ALTER TABLE public.signingfiles
            ADD CONSTRAINT signingfiles_lawyerid_fkey
            FOREIGN KEY (lawyerid) REFERENCES public.users(userid);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'signingfiles_clientid_fkey'
    ) THEN
        ALTER TABLE public.signingfiles
            ADD CONSTRAINT signingfiles_clientid_fkey
            FOREIGN KEY (clientid) REFERENCES public.users(userid);
    END IF;
END$$;

-- Helpful indexes used by list endpoints
CREATE INDEX IF NOT EXISTS idx_signingfiles_lawyerid_createdat
    ON public.signingfiles (lawyerid, createdat DESC);

CREATE INDEX IF NOT EXISTS idx_signingfiles_clientid_createdat
    ON public.signingfiles (clientid, createdat DESC);


-- 2) signaturespots
CREATE TABLE IF NOT EXISTS public.signaturespots (
    signaturespotid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signingfileid INTEGER NOT NULL,
    pagenumber INTEGER NOT NULL DEFAULT 1,
    x DOUBLE PRECISION NOT NULL DEFAULT 0,
    y DOUBLE PRECISION NOT NULL DEFAULT 0,
    width DOUBLE PRECISION NOT NULL DEFAULT 150,
    height DOUBLE PRECISION NOT NULL DEFAULT 75,
    signername TEXT,
    isrequired BOOLEAN NOT NULL DEFAULT TRUE,
    issigned BOOLEAN NOT NULL DEFAULT FALSE,
    signaturedata TEXT,
    signedat TIMESTAMPTZ,
    createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    signeruserid INTEGER
);

-- Ensure required columns exist even if the table pre-existed.
ALTER TABLE IF EXISTS public.signaturespots
    ADD COLUMN IF NOT EXISTS signingfileid INTEGER,
    ADD COLUMN IF NOT EXISTS pagenumber INTEGER,
    ADD COLUMN IF NOT EXISTS x DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS y DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS width DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS height DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS signername TEXT,
    ADD COLUMN IF NOT EXISTS isrequired BOOLEAN,
    ADD COLUMN IF NOT EXISTS issigned BOOLEAN,
    ADD COLUMN IF NOT EXISTS signaturedata TEXT,
    ADD COLUMN IF NOT EXISTS signedat TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS signeruserid INTEGER;

-- Ensure defaults going forward (safe even if already set)
ALTER TABLE IF EXISTS public.signaturespots
    ALTER COLUMN isrequired SET DEFAULT TRUE,
    ALTER COLUMN issigned SET DEFAULT FALSE;

-- Backfill defaults for existing rows (if any)
UPDATE public.signaturespots
SET isrequired = TRUE
WHERE isrequired IS NULL;

UPDATE public.signaturespots
SET issigned = FALSE
WHERE issigned IS NULL;

-- Constraints (idempotent via names)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'signaturespots_signingfileid_fkey'
    ) THEN
        ALTER TABLE public.signaturespots
            ADD CONSTRAINT signaturespots_signingfileid_fkey
            FOREIGN KEY (signingfileid) REFERENCES public.signingfiles(signingfileid)
            ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'signaturespots_signeruserid_fkey'
    ) THEN
        ALTER TABLE public.signaturespots
            ADD CONSTRAINT signaturespots_signeruserid_fkey
            FOREIGN KEY (signeruserid) REFERENCES public.users(userid)
            ON DELETE SET NULL;
    END IF;
END$$;

-- Indexes for common reads
CREATE INDEX IF NOT EXISTS idx_signaturespots_signingfileid
    ON public.signaturespots (signingfileid);

CREATE INDEX IF NOT EXISTS idx_signaturespots_signingfileid_required_signed
    ON public.signaturespots (signingfileid, isrequired, issigned);

CREATE INDEX IF NOT EXISTS idx_signaturespots_signeruserid
    ON public.signaturespots (signeruserid);
