-- Calendar invite + reminder HTML email templates (editable in Platform Settings).
-- Placeholders use [[snake_case]] to match other email_templates rows.
-- [[nav_buttons]] / [[rsvp_button]] are pre-built CTA HTML (never raw map query strings).

INSERT INTO email_templates (template_key, label, subject_template, available_vars, html_body)
VALUES (
    'CALENDAR_INVITE',
    'הזמנה לפגישה (יומן)',
    'הזמנה לפגישה — [[title]]',
    '["recipient_name","clients_names","date","time","address","title","lawyer_name","firm_name","firm_phone","website_url","waze_url","maps_url","rsvp_url","firm_logo_url","nav_buttons","rsvp_button"]',
    E'<!DOCTYPE html>\n<html dir="rtl" lang="he">\n<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="x-apple-disable-message-reformatting"><title>הזמנה לפגישה</title></head>\n<body style="margin:0;padding:0;background-color:#EDF2F7;">\n<table border="0" cellpadding="0" cellspacing="0" style="background:#EDF2F7;" width="100%"><tbody><tr><td align="center" style="padding:24px 12px;">\n<table border="0" cellpadding="0" cellspacing="0" style="width:640px;max-width:100%;background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 6px 18px rgba(0,0,0,0.08);" width="640"><tbody>\n<tr><td style="background:#2A4365;padding:22px 24px;text-align:center;"><img src="[[firm_logo_url]]" width="170" alt="[[firm_name]]" style="border:0;outline:none;text-decoration:none;height:auto;max-width:100%;"><div style="height:14px;line-height:14px;">&nbsp;</div><div style="font-family:system-ui,-apple-system,BlinkMacSystemFont,''Segoe UI'',Roboto,Arial,sans-serif;color:#FFFFFF;font-size:18px;font-weight:600;line-height:1.4;">הזמנה לפגישה</div></td></tr>\n<tr><td style="padding:26px 24px 8px 24px;font-family:system-ui,-apple-system,BlinkMacSystemFont,''Segoe UI'',Roboto,Arial,sans-serif;color:#2D3748;"><div style="font-size:16px;line-height:1.7;">שלום [[recipient_name]],<br><br>נקבעה לך פגישה: <span style="font-weight:600;color:#1A365D;">[[title]]</span><br>תאריך: <span style="font-weight:600;color:#1A365D;">[[date]]</span> בשעה <span style="font-weight:600;color:#1A365D;">[[time]]</span><br>כתובת: <span style="font-weight:600;">[[address]]</span><br>עו״ד מטפל: <span style="font-weight:600;">[[lawyer_name]]</span></div><div style="height:18px;line-height:18px;">&nbsp;</div>[[rsvp_button]][[nav_buttons]]<div style="height:10px;line-height:10px;">&nbsp;</div><div style="font-size:13px;line-height:1.7;color:#718096;">לבירור או שינוי ניתן להתקשר ל־[[firm_phone]]</div><div style="height:18px;line-height:18px;">&nbsp;</div></td></tr>\n<tr><td style="padding:14px 24px 22px 24px;font-family:system-ui,-apple-system,BlinkMacSystemFont,''Segoe UI'',Roboto,Arial,sans-serif;color:#718096;font-size:12px;line-height:1.7;">הודעה זו נשלחה אוטומטית.<br>&copy; [[firm_name]]</td></tr>\n</tbody></table>\n</td></tr></tbody></table>\n</body>\n</html>'
) ON CONFLICT (template_key) DO NOTHING;

INSERT INTO email_templates (template_key, label, subject_template, available_vars, html_body)
VALUES (
    'CALENDAR_REMINDER',
    'תזכורת לפגישה (יומן)',
    'תזכורת לפגישה — [[title]]',
    '["recipient_name","clients_names","date","time","address","title","lawyer_name","firm_name","firm_phone","website_url","waze_url","maps_url","rsvp_url","firm_logo_url","nav_buttons","rsvp_button","when_label"]',
    E'<!DOCTYPE html>\n<html dir="rtl" lang="he">\n<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="x-apple-disable-message-reformatting"><title>תזכורת לפגישה</title></head>\n<body style="margin:0;padding:0;background-color:#EDF2F7;">\n<table border="0" cellpadding="0" cellspacing="0" style="background:#EDF2F7;" width="100%"><tbody><tr><td align="center" style="padding:24px 12px;">\n<table border="0" cellpadding="0" cellspacing="0" style="width:640px;max-width:100%;background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 6px 18px rgba(0,0,0,0.08);" width="640"><tbody>\n<tr><td style="background:#2A4365;padding:22px 24px;text-align:center;"><img src="[[firm_logo_url]]" width="170" alt="[[firm_name]]" style="border:0;outline:none;text-decoration:none;height:auto;max-width:100%;"><div style="height:14px;line-height:14px;">&nbsp;</div><div style="font-family:system-ui,-apple-system,BlinkMacSystemFont,''Segoe UI'',Roboto,Arial,sans-serif;color:#FFFFFF;font-size:18px;font-weight:600;line-height:1.4;">תזכורת לפגישה</div></td></tr>\n<tr><td style="padding:26px 24px 8px 24px;font-family:system-ui,-apple-system,BlinkMacSystemFont,''Segoe UI'',Roboto,Arial,sans-serif;color:#2D3748;"><div style="font-size:16px;line-height:1.7;">שלום [[recipient_name]],<br><br>זוהי תזכורת לפגישה שנקבעה עבורך ב־<span style="font-weight:600;color:#1A365D;">[[firm_name]]</span>.<br>נושא: <span style="font-weight:600;color:#1A365D;">[[title]]</span><br>תאריך: <span style="font-weight:600;color:#1A365D;">[[date]]</span> בשעה <span style="font-weight:600;color:#1A365D;">[[time]]</span><br>כתובת: <span style="font-weight:600;">[[address]]</span></div><div style="height:18px;line-height:18px;">&nbsp;</div>[[nav_buttons]]<div style="height:10px;line-height:10px;">&nbsp;</div><div style="font-size:13px;line-height:1.7;color:#718096;">לבירור או שינוי נא להתקשר ל־[[firm_phone]]</div><div style="height:18px;line-height:18px;">&nbsp;</div></td></tr>\n<tr><td style="padding:14px 24px 22px 24px;font-family:system-ui,-apple-system,BlinkMacSystemFont,''Segoe UI'',Roboto,Arial,sans-serif;color:#718096;font-size:12px;line-height:1.7;">הודעה זו נשלחה אוטומטית.<br>&copy; [[firm_name]]</td></tr>\n</tbody></table>\n</td></tr></tbody></table>\n</body>\n</html>'
) ON CONFLICT (template_key) DO NOTHING;

INSERT INTO email_templates (template_key, label, subject_template, available_vars, html_body)
VALUES (
    'CALENDAR_LAWYER_REMINDER',
    'תזכורת יומן לעורך דין',
    'תזכורת מהיומן — [[title]]',
    '["recipient_name","clients_names","date","time","address","title","lawyer_name","firm_name","firm_phone","website_url","waze_url","maps_url","firm_logo_url","nav_buttons","when_label","body_text"]',
    E'<!DOCTYPE html>\n<html dir="rtl" lang="he">\n<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="x-apple-disable-message-reformatting"><title>תזכורת מהיומן</title></head>\n<body style="margin:0;padding:0;background-color:#EDF2F7;">\n<table border="0" cellpadding="0" cellspacing="0" style="background:#EDF2F7;" width="100%"><tbody><tr><td align="center" style="padding:24px 12px;">\n<table border="0" cellpadding="0" cellspacing="0" style="width:640px;max-width:100%;background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 6px 18px rgba(0,0,0,0.08);" width="640"><tbody>\n<tr><td style="background:#2A4365;padding:22px 24px;text-align:center;"><img src="[[firm_logo_url]]" width="170" alt="[[firm_name]]" style="border:0;outline:none;text-decoration:none;height:auto;max-width:100%;"><div style="height:14px;line-height:14px;">&nbsp;</div><div style="font-family:system-ui,-apple-system,BlinkMacSystemFont,''Segoe UI'',Roboto,Arial,sans-serif;color:#FFFFFF;font-size:18px;font-weight:600;line-height:1.4;">תזכורת מהיומן</div></td></tr>\n<tr><td style="padding:26px 24px 8px 24px;font-family:system-ui,-apple-system,BlinkMacSystemFont,''Segoe UI'',Roboto,Arial,sans-serif;color:#2D3748;"><div style="font-size:16px;line-height:1.7;">שלום [[recipient_name]],<br><br>[[body_text]]<br><br>נושא: <span style="font-weight:600;color:#1A365D;">[[title]]</span><br>לקוחות: <span style="font-weight:600;color:#1A365D;">[[clients_names]]</span><br>תאריך: <span style="font-weight:600;color:#1A365D;">[[date]]</span> בשעה <span style="font-weight:600;color:#1A365D;">[[time]]</span><br>כתובת: <span style="font-weight:600;">[[address]]</span><br>תזמון: <span style="font-weight:600;">[[when_label]]</span></div><div style="height:18px;line-height:18px;">&nbsp;</div>[[nav_buttons]]<div style="height:18px;line-height:18px;">&nbsp;</div></td></tr>\n<tr><td style="padding:14px 24px 22px 24px;font-family:system-ui,-apple-system,BlinkMacSystemFont,''Segoe UI'',Roboto,Arial,sans-serif;color:#718096;font-size:12px;line-height:1.7;">הודעה זו נשלחה אוטומטית.<br>&copy; [[firm_name]]</td></tr>\n</tbody></table>\n</td></tr></tbody></table>\n</body>\n</html>'
) ON CONFLICT (template_key) DO NOTHING;
